version: "3.6"
services:
  web:
    image: <%= dockerRegistryPath %>/<%= projectName %>_api
    secrets:
      - source: <%= projectName %>_sslcert.cert
        target: sslcert.cert
      - source: <%= projectName %>_sslcert.key
        target: sslcert.key
      - source: <%= projectName %>_users.json
        target: users.json
    configs:
      - source: <%= projectName %>_config
        target: /run/config.json
    deploy:
      replicas: <%= instanceCount %>
      <% if (instanceCount == 1) { %>
      placement:
        constraints: [node.role == manager]
      <% } %>
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "<%= tcpPort %>:3000"
    networks:
      - <%= projectName %>_net
    environment:
      - TZ=<%= timeZone %>
    <% if (enableALA) { %>
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:25225"
        tag: oms.api.applogging
    <% } %>
networks:
  <%= projectName %>_net:
secrets:
  <%= projectName %>_sslcert.cert:
    external: true

  <%= projectName %>_sslcert.key: 
    external: true
    
  <%= projectName %>_users.json:
    external: true
configs:
  <%= projectName %>_config:
    external: true